language: node_js

node_js: '8.10'

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10-postgis-2.4
      - proj-bin
      - postgresql-10-postgis-2.4-scripts

before_install:
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - export PGPORT=5433
  - if [[ $TRAVIS_BRANCH != 'master' ]]; then BRANCH='dev'; else BRANCH='master'; fi;
  - export PGDATABASE=cognicity_server_testing ; git clone -b $BRANCH https://github.com/urbanriskmap/cognicity-schema.git && cd cognicity-schema && bash build/run.sh && cd -

install:
  - npm install

script:
  - npm run integration
  - npm run test && npm run coverage
