# CogniCity Sensors Endpoint
service: cognicity-sensors

custom:
  projectName: cognicity-sensors

# AWS parameters
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ${file(./.env.yml):region}
  stackTags:
    area: ${file(./.env.yml):area_tag}
  vpc:
    securityGroupIds:
      - ${file(./.env.yml):securityGroupIds}
    subnetIds:
      - ${file(./.env.yml):subnetIdA}
      - ${file(./.env.yml):subnetIdB}
  apiKeys:
    - ${file(./.env.yml):apiKey}
  usagePlan:
    burstLimit: 150
    rateLimit: 100

# Add one function for each Lambda
# TODO - rate limits
# TODO - caching
functions:
  testQuery: # Lambda that tests query
    timeout: ${file(./.env.yml):timeout}
    environment:
        PGHOST: ${file(./.env.yml):PGHOST}
        PGDATABASE: ${file(./.env.yml):PGDATABASE}
        PGPASSWORD: ${file(./.env.yml):PGPASSWORD}
        PGPORT: ${file(./.env.yml):PGPORT}
        PGSSL: ${file(./.env.yml):PGSSL}
        PGTIMEOUT: ${file(./.env.yml):PGTIMEOUT}
        PGUSER: ${file(./.env.yml):PGUSER}
    handler: bin/functions/testQuery.default
    events:
        - http:
            cors: true
            path: testing
            method: GET
            integration: lambda
  getSensors: # Lambda that gets sensors
    timeout: ${file(./.env.yml):timeout}
    environment:
        PGHOST: ${file(./.env.yml):PGHOST}
        PGDATABASE: ${file(./.env.yml):PGDATABASE}
        PGPASSWORD: ${file(./.env.yml):PGPASSWORD}
        PGPORT: ${file(./.env.yml):PGPORT}
        PGSSL: ${file(./.env.yml):PGSSL}
        PGTIMEOUT: ${file(./.env.yml):PGTIMEOUT}
        PGUSER: ${file(./.env.yml):PGUSER}
    handler: bin/functions/getSensors.default
    events:
      - http:
          cors: true
          path: sensors
          method: GET
          integration: lambda
          parameters:
            querystrings:
              bbox: false # optional
              format: false # optional
  getSensorData: # Lambda that gets sensor data
    timeout: ${file(./.env.yml):timeout}
    environment:
        PGHOST: ${file(./.env.yml):PGHOST}
        PGDATABASE: ${file(./.env.yml):PGDATABASE}
        PGPASSWORD: ${file(./.env.yml):PGPASSWORD}
        PGPORT: ${file(./.env.yml):PGPORT}
        PGSSL: ${file(./.env.yml):PGSSL}
        PGTIMEOUT: ${file(./.env.yml):PGTIMEOUT}
        PGUSER: ${file(./.env.yml):PGUSER}
    handler: bin/functions/getSensorData.default
    events:
      - http:
          cors: true
          path: sensors/{id}
          method: GET
          integration: lambda
          parameters:
            paths:
              id: true
  addSensor: # Lambda that posts sensor metadata
    timeout: ${file(./.env.yml):timeout}
    environment:
        PGHOST: ${file(./.env.yml):PGHOST}
        PGDATABASE: ${file(./.env.yml):PGDATABASE}
        PGPASSWORD: ${file(./.env.yml):PGPASSWORD}
        PGPORT: ${file(./.env.yml):PGPORT}
        PGSSL: ${file(./.env.yml):PGSSL}
        PGTIMEOUT: ${file(./.env.yml):PGTIMEOUT}
        PGUSER: ${file(./.env.yml):PGUSER}
    handler: bin/functions/addSensor.default
    events:
      - http:
          cors: true
          path: sensors/
          method: POST
          integration: lambda
          private: true
  addSensorData: # Lambda that gets sensor data
    timeout: ${file(./.env.yml):timeout}
    environment:
        PGHOST: ${file(./.env.yml):PGHOST}
        PGDATABASE: ${file(./.env.yml):PGDATABASE}
        PGPASSWORD: ${file(./.env.yml):PGPASSWORD}
        PGPORT: ${file(./.env.yml):PGPORT}
        PGSSL: ${file(./.env.yml):PGSSL}
        PGTIMEOUT: ${file(./.env.yml):PGTIMEOUT}
        PGUSER: ${file(./.env.yml):PGUSER}
    handler: bin/functions/addSensorData.default
    events:
      - http:
          cors: true
          path: sensors/{id}
          method: POST
          integration: lambda
          private: true
          parameters:
            paths:
              id: true
  deleteSensorData: # Lambda that gets sensor data
    timeout: ${file(./.env.yml):timeout}
    environment:
        PGHOST: ${file(./.env.yml):PGHOST}
        PGDATABASE: ${file(./.env.yml):PGDATABASE}
        PGPASSWORD: ${file(./.env.yml):PGPASSWORD}
        PGPORT: ${file(./.env.yml):PGPORT}
        PGSSL: ${file(./.env.yml):PGSSL}
        PGTIMEOUT: ${file(./.env.yml):PGTIMEOUT}
        PGUSER: ${file(./.env.yml):PGUSER}
    handler: bin/functions/deleteSensorData.default
    events:
      - http:
          cors: true
          path: sensors/{id}
          method: DELETE
          integration: lambda
          private: true
          parameters:
            paths:
              id: true

